services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dhwalief/pojokbuku-app:v0.21
    container_name: pojokbuku-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pojokbuku

  db:
    image: mysql:8.0
    container_name: pojokbuku-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - pojokbuku

  nginx:
    image: nginx:alpine
    container_name: pojokbuku-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - pojokbuku

networks:
  pojokbuku:
    driver: bridge

